export const ALBUM = {
  PENDING: "LOAD_ALBUM_PENDING",
  SUCCESS: "LOAD_ALBUM_SUCCESS",
  ERROR: "LOAD_ALBUM_ERROR",
};

export const NEW_RELEASES = {
  PENDING: "LOAD_NEW_RELEASES_PENDING",
  SUCCESS: "LOAD_NEW_RELEASES_SUCCESS",
  ERROR: "LOAD_NEW_RELEASES_ERROR",
  LOAD_MORE_PENDING: "LOAD_MORE_NEW_RELEASES_PENDING",
  LOAD_MORE_SUCCESS: "LOAD_MORE_NEW_RELEASES_SUCCESS",
  LOAD_MORE_ERROR: "LOAD_MORE_NEW_RELEASES_ERROR",
};

export const ARTIST_ALBUMS = {
  PENDING: "LOAD_ARTIST_ALBUMS_PENDING",
  SUCCESS: "LOAD_ARTIST_ALBUMS_SUCCESS",
  ERROR: "LOAD_ARTIST_ALBUMS_ERROR",
  LOAD_MORE_PENDING: "LOAD_MORE_ARTIST_ALBUMS_PENDING",
  LOAD_MORE_SUCCESS: "LOAD_MORE_ARTIST_ALBUMS_SUCCESS",
  LOAD_MORE_ERROR: "LOAD_MORE_ARTIST_ALBUMS_ERROR",
};

export const ARTIST_SINGLES = {
  PENDING: "LOAD_ARTIST_SINGLES_PENDING",
  SUCCESS: "LOAD_ARTIST_SINGLES_SUCCESS",
  ERROR: "LOAD_ARTIST_SINGLES_ERROR",
  LOAD_MORE_PENDING: "LOAD_MORE_ARTIST_SINGLES_PENDING",
  LOAD_MORE_SUCCESS: "LOAD_MORE_ARTIST_SINGLES_SUCCESS",
  LOAD_MORE_ERROR: "LOAD_MORE_ARTIST_SINGLES_ERROR",
};

export const ADD_TO_MY_SAVED_ALBUMS = "ADD_TO_MY_SAVED_ALBUMS";
export const REMOVE_FROM_MY_SAVED_ALBUMS = "REMOVE_FROM_MY_SAVED_ALBUMS";

export const ARTIST = {
  PENDING: "LOAD_ARTIST_PENDING",
  SUCCESS: "LOAD_ARTIST_SUCCESS",
  ERROR: "LOAD_ARTIST_ERROR",
};

export const FOLLOWED_ARTISTS = {
  PENDING: "LOAD_FOLLOWED_ARTISTS_PENDING",
  SUCCESS: "LOAD_FOLLOWED_ARTISTS_SUCCESS",
  ERROR: "LOAD_FOLLOWED_ARTISTS_ERROR",
  LOAD_MORE_PENDING: "LOAD_MORE_FOLLOWED_ARTISTS_PENDING",
  LOAD_MORE_SUCCESS: "LOAD_MORE_FOLLOWED_ARTISTS_SUCCESS",
  LOAD_MORE_ERROR: "LOAD_MORE_FOLLOWED_ARTISTS_ERROR",
};

export const RELATED_ARTISTS = {
  PENDING: "LOAD_RELATED_ARTISTS_PENDING",
  SUCCESS: "LOAD_RELATED_ARTISTS_SUCCESS",
  ERROR: "LOAD_RELATED_ARTISTS_ERROR",
};

export const FOLLOW_ARTIST = "FOLLOW_ARTIST";
export const UNFOLLOW_ARTIST = "UNFOLLOW_ARTIST";

export const CATEGORIES = {
  PENDING: "LOAD_CATEGORIES_PENDING",
  SUCCESS: "LOAD_CATEGORIES_SUCCESS",
  ERROR: "LOAD_CATEGORIES_ERROR",
  LOAD_MORE_PENDING: "LOAD_MORE_CATEGORIES_PENDING",
  LOAD_MORE_SUCCESS: "LOAD_MORE_CATEGORIES_SUCCESS",
  LOAD_MORE_ERROR: "LOAD_MORE_CATEGORIES_ERROR",
};

export const FILTER_BY_COUNTRY = "FILTER_BY_COUNTRY";

export const PLAYER = {
  PLAY: "PLAY_TRACK",
  PAUSE: "PAUSE_TRACK",
  RESUME: "RESUME_TRACK",
  SET_CONTEXT: "SET_CONTEXT",
  UPDATE_CONTEXT: "UPDATE_CONTEXT",
  CHANGE_CURRENT_TIME: "CHANGE_CURRENT_TIME",
  TOGGLE_REPEAT: "TOGGLE_REPEAT",
};

export const CATEGORY_PLAYLISTS = {
  PENDING: "LOAD_CATEGORY_PLAYLISTS_PENDING",
  SUCCESS: "LOAD_CATEGORY_PLAYLISTS_SUCCESS",
  ERROR: "LOAD_CATEGORY_PLAYLISTS_ERROR",
  LOAD_MORE_PENDING: "LOAD_MORE_CATEGORY_PLAYLISTS_PENDING",
  LOAD_MORE_SUCCESS: "LOAD_MORE_CATEGORY_PLAYLISTS_SUCCESS",
  LOAD_MORE_ERROR: "LOAD_MORE_CATEGORY_PLAYLISTS_ERROR",
};

export const PLAYLIST = {
  PENDING: "LOAD_PLAYLIST_PENDING",
  SUCCESS: "LOAD_PLAYLIST_SUCCESS",
  ERROR: "LOAD_PLAYLIST_ERROR",
};

export const FEATURED_PLAYLISTS = {
  PENDING: "LOAD_FEATURED_PLAYLISTS_PENDING",
  SUCCESS: "LOAD_FEATURED_PLAYLISTS_SUCCESS",
  ERROR: "LOAD_FEATURED_PLAYLISTS_ERROR",
};

export const USER_PLAYLISTS = {
  PENDING: "LOAD_USER_PLAYLISTS_PENDING",
  SUCCESS: "LOAD_USER_PLAYLISTS_SUCCESS",
  ERROR: "LOAD_USER_PLAYLISTS_ERROR",
  LOAD_MORE_PENDING: "LOAD_MORE_USER_PLAYLISTS_PENDING",
  LOAD_MORE_SUCCESS: "LOAD_MORE_USER_PLAYLISTS_SUCCESS",
  LOAD_MORE_ERROR: "LOAD_MORE_USER_PLAYLISTS_ERROR",
};

export const LIST_USER_PLAYLISTS = {
  PENDING: "LOAD_LIST_USER_PLAYLISTS_PENDING",
  SUCCESS: "LOAD_LIST_USER_PLAYLISTS_SUCCESS",
  ERROR: "LOAD_USER_PLAYLISTS_ERROR",
  LOAD_MORE_PENDING: "LOAD_MORE_LIST_USER_PLAYLISTS_PENDING",
  LOAD_MORE_SUCCESS: "LOAD_MORE_LIST_USER_PLAYLISTS_SUCCESS",
  LOAD_MORE_ERROR: "LOAD_MORE_LIST_USER_PLAYLISTS_ERROR",
};

export const UPLOAD_PLAYLIST_COVER = "UPLOAD_PLAYLIST_COVER";

export const CHANGE_PLAYLIST_DETAILS = "CHANGE_PLAYLIST_DETAILS";

export const ADD_TRACK_TO_PLAYLIST = "ADD_TRACK_TO_PLAYLIST";
export const REMOVE_TRACK_FROM_PLAYLIST = "REMOVE_TRACK_FROM_PLAYLIST";

export const FOLLOW_PLAYLIST = "FOLLOW_PLAYLIST";
export const UNFOLLOW_PLAYLIST = "UNFOLLOW_PLAYLIST";

export const CREATE_PLAYLIST = "CREATE_PLAYLIST";

export const SEARCH_RESULTS = {
  PENDING: "LOAD_SEARCH_RESULTS_PENDING",
  SUCCESS: "LOAD_SEARCH_RESULTS_SUCCESS",
  ERROR: "LOAD_SEARCH_RESULTS_ERROR",
};

export const FILTER_BY_TYPE = "FILTER_BY_TYPE";
export const RESET_SEARCH_RESULTS = "RESET_SEARCH_RESULTS";
export const TOGGLE_SEARCH = "TOGGLE_SEARCH";

export const TOP_TRACKS = {
  PENDING: "LOAD_TOP_TRACKS_PENDING",
  SUCCESS: "LOAD_TOP_TRACKS_SUCCESS",
  ERROR: "LOAD_TOP_TRACKS_ERROR",
  LOAD_MORE_PENDING: "LOAD_MORE_TOP_TRACKS_PENDING",
  LOAD_MORE_SUCCESS: "LOAD_MORE_TOP_TRACKS_SUCCESS",
  LOAD_MORE_ERROR: "LOAD_MORE_TOP_TRACKS_ERROR",
};

export const SAVED_TRACKS = {
  PENDING: "LOAD_SAVED_TRACKS_PENDING",
  SUCCESS: "LOAD_SAVED_TRACKS_SUCCESS",
  ERROR: "LOAD_SAVED_TRACKS_ERROR",
  LOAD_MORE_PENDING: "LOAD_MORE_SAVED_TRACKS_PENDING",
  LOAD_MORE_SUCCESS: "LOAD_MORE_SAVED_TRACKS_SUCCESS",
  LOAD_MORE_ERROR: "LOAD_MORE_SAVED_TRACKS_ERROR",
};

export const ARTIST_TOP_TRACKS = {
  PENDING: "LOAD_ARTIST_TOP_TRACKS_PENDING",
  SUCCESS: "LOAD_ARTIST_TOP_TRACKS_SUCCESS",
  ERROR: "LOAD_ARTIST_TOP_TRACKS_ERROR",
};

export const ALBUM_TRACKS = {
  PENDING: "LOAD_ALBUM_TRACKS_PENDING",
  SUCCESS: "LOAD_ALBUM_TRACKS_SUCCESS",
  ERROR: "LOAD_ALBUM_TRACKS_ERROR",
};

export const PLAYLIST_TRACKS = {
  PENDING: "LOAD_PLAYLIST_TRACKS_PENDING",
  SUCCESS: "LOAD_PLAYLIST_TRACKS_SUCCESS",
  ERROR: "LOAD_PLAYLIST_TRACKS_ERROR",
  LOAD_MORE_PENDING: "LOAD_MORE_PLAYLIST_TRACKS_PENDING",
  LOAD_MORE_SUCCESS: "LOAD_MORE_PLAYLIST_TRACKS_SUCCESS",
  LOAD_MORE_ERROR: "LOAD_MORE_PLAYLIST_TRACKS_ERROR",
};

export const ADD_TO_FAVORITE_TRACKS = "ADD_TO_FAVORITE_TRACKS";
export const REMOVE_FROM_FAVORITE_TRACKS = "REMOVE_FROM_FAVORITE_TRACKS";